package org.eclipse.scout.myapp.shared.helloworld.color;

import java.awt.Color;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.eclipse.scout.myapp.client.helloworld.color.BaseColorTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class BaseColorTablePageData extends AbstractTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public BaseColorTableRowData addRow() {
		return (BaseColorTableRowData) super.addRow();
	}

	@Override
	public BaseColorTableRowData addRow(int rowState) {
		return (BaseColorTableRowData) super.addRow(rowState);
	}

	@Override
	public BaseColorTableRowData createRow() {
		return new BaseColorTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return BaseColorTableRowData.class;
	}

	@Override
	public BaseColorTableRowData[] getRows() {
		return (BaseColorTableRowData[]) super.getRows();
	}

	@Override
	public BaseColorTableRowData rowAt(int index) {
		return (BaseColorTableRowData) super.rowAt(index);
	}

	public void setRows(BaseColorTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class BaseColorTableRowData extends AbstractTableRowData {

		private static final long serialVersionUID = 1L;
		public static final String id = "id";
		public static final String redValue = "redValue";
		public static final String greenValue = "greenValue";
		public static final String blueValue = "blueValue";
		public static final String color = "color";
		private Color m_id;
		private Integer m_redValue;
		private Integer m_greenValue;
		private Integer m_blueValue;
		private Color m_color;

		public Color getId() {
			return m_id;
		}

		public void setId(Color newId) {
			m_id = newId;
		}

		public Integer getRedValue() {
			return m_redValue;
		}

		public void setRedValue(Integer newRedValue) {
			m_redValue = newRedValue;
		}

		public Integer getGreenValue() {
			return m_greenValue;
		}

		public void setGreenValue(Integer newGreenValue) {
			m_greenValue = newGreenValue;
		}

		public Integer getBlueValue() {
			return m_blueValue;
		}

		public void setBlueValue(Integer newBlueValue) {
			m_blueValue = newBlueValue;
		}

		public Color getColor() {
			return m_color;
		}

		public void setColor(Color newColor) {
			m_color = newColor;
		}
	}
}
