package org.eclipse.scout.myapp.shared.helloworld.color;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.eclipse.scout.myapp.client.helloworld.color.ColorSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ColorSearchFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	public BlueOperator getBlueOperator() {
		return getFieldByClass(BlueOperator.class);
	}

	public BlueValue getBlueValue() {
		return getFieldByClass(BlueValue.class);
	}

	public Color getColor() {
		return getFieldByClass(Color.class);
	}

	public GreenOperator getGreenOperator() {
		return getFieldByClass(GreenOperator.class);
	}

	public GreenValue getGreenValue() {
		return getFieldByClass(GreenValue.class);
	}

	public RedOperator getRedOperator() {
		return getFieldByClass(RedOperator.class);
	}

	public RedValue getRedValue() {
		return getFieldByClass(RedValue.class);
	}

	public static class BlueOperator extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class BlueValue extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class Color extends AbstractValueFieldData<java.awt.Color> {

		private static final long serialVersionUID = 1L;
	}

	public static class GreenOperator extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class GreenValue extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}

	public static class RedOperator extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class RedValue extends AbstractValueFieldData<Long> {

		private static final long serialVersionUID = 1L;
	}
}
